# AI Developer Productivity, Task Success, and Emerging Technology Trends📝

![Banner](./assets/banner.jpeg)

## Topic
*What problem are you (or your stakeholder) trying to address?*
📝 <!-- Answer Below -->

As we observe, AI has changed the way developers build software from writing line by line to architect complex solutions, they can work faster and more efficiently. With the way things are going, lots of ideas and creative technologies have been created. Nowadays, developers can use tools like AI models to help generate code, code review, debug errors, create tests, and even architecture design. 

The problem I tried to study is to find out if increased use of AI tools is actually associated with higher developers productivity or if it brings more issues related to additional debugging, verification, and rework.

This project aims to use metrics such as coding time, AI usage, bugs reported, and task success to examine developer productivity and its relationship with AI development tools. In addition, the project will examine real-world AI use development activity through Copilot-authored pull requests, using metrics such as pull request merge time, commits, and changed files.

## Project Question
*What specific question are you seeking to answer with this project?*
*This is not the same as the questions you ask to limit the scope of the project.*
📝 <!-- Answer Below -->

I'd like to ask how AI usage is changing software developement in term of developer productivity, developer experience, and technology trends.
The analysis will:
- Analyze how AI usage is related to implementation time, post-review work, perceived effort, and task completion.

- Examine developers’ AI usage, trust, frustrations, perceived productivity, and experience.

- Examine real-world AI-assisted development activity through Copilot-authored pull requests, focusing on merge time, commits, and changed files.

## What would an answer look like?
*What is your hypothesized answer to your question?*
📝 <!-- Answer Below -->

My hypothesis is that the increased use of AI development tools will generally be associated with higher productivity and faster task completion. Along with that, I expect the increased use of AI may introduce additional debugging, verification, or code-quality problems.

Therefore, I think the results will show that AI can improve productivity while also bringing tradeoffs.

Some answers may be:
- Developers with AI usage may complete the initial implementation faster.

- AI usage may affect the amount of time spent making changes after code review.

- Developers may perceive AI as improving productivity even when measured productivity shows mixed results.

- Higher AI usage may also introduce additional debugging or quality-related concerns.
- Copilot-authored pull requests may show different merge-time patterns depending on the size and complexity of the contribution.

This project aims to study about the correlation and relationships, rather than claiming that AI directly changes developer productivity.

## Data Sources

This project will use three data sources:

- METR Developer Productivity Study (CSV) will be used to collect developer productivity which includes tasks completed with and without AI assistance.

- Stack Overflow Developer Survey 2025 (CSV) will be used to examine developers' use of AI tools, trust in AI output, etc. 

- GitHub REST API (API) will be used to retrieve real-world development activity related to AI coding agents (GitHub Copilot).

The datasets will not be directly merged but instead, their results will be used to compare in the final analysis to provide different perspectives on how AI is affecting software development.

## Approach and Analysis
*What is your approach to answering your project question?*
*How will you use the identified data to answer your project question?*
📝 <!-- Start Discussing the project here; you can add as many code cells as you need -->

- METR Developer Productivity Study: this data source provides a list of developers with AI and non-AI usage. I can use metrics like `implementation time`, `post-review time`, `task completion`, and `perceived effort` to compare productivity between these two groups. Bar charts may be used to support the analysis through visualization.

- Stack Overflow Developer Survey 2025: used to examine `AI usage`, `trust`, `frustrations`, `perceived productivity`, and `developer experience`. This can be used to compare responses across different groups of developers and examine how developers perceive the impact of AI tools on their productivity.

- GitHub REST API: used to examine real-world software development activity involving AI coding agents. I will retrieve Copilot-authored pull request data, including `creation time`, `merge time`, `commits`, and `changed files`. These metrics can be used to identify patterns in AI usage development activity on real-world GitHub repositories, such as how long Copilot-authored pull requests take to be merged and how pull request size or complexity relates to merge time. Bar charts and distribution plots may be used to visualize these patterns.

# Setup and Import Libraries

In [26]:
# Import libraries
import numpy as np
import pandas as pd
import requests

# Import dataset

### Import METR Data - Open Source Developer Productivity Data

In [21]:
metr_df = pd.read_csv("data/raw/osdp.csv")
metr_df.shape

(1134, 14)

In [22]:
metr_df.head()

,id,developerId,treatmentAssignment,status,priorExperience,estimatedTimeWithAI,estimatedTimeWithoutAI,createdAt,lastModified,initialImplementationTime,postReviewImplementationTime,estimatedTimeOtherTreatment,perceivedEffort,isPanelDeveloper
0,47a33fef-793f-429c-98e7-f778bbcc52d5,54,AI-disallowed,complete,4.0,50.0,50.0,2025-08-12,2025-08-13,77.0,30.0,90.0,3.0,True
1,25e419a1-4ceb-4111-98d6-14e9f24d3d72,38,AI-allowed,incomplete,2.0,60.0,70.0,2025-08-12,2025-08-12,24.0,NaN,NaN,NaN,True
2,640fda7c-2b07-4fc3-85f6-b1e347247ba6,3,AI-disallowed,complete,4.0,60.0,60.0,2025-08-12,2025-08-20,188.0,0.0,160.0,2.0,True
3,10df330a-d84c-41d2-8557-b311e54fc289,12,AI-allowed,complete,3.0,330.0,300.0,2025-08-13,2025-11-12,648.0,0.0,500.0,4.0,True
4,edd974a5-04b7-4c7c-994b-51d78eef79de,54,AI-allowed,incomplete,5.0,20.0,20.0,2025-08-13,2025-08-13,25.0,NaN,NaN,4.0,True

In [23]:
metr_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1134 entries, 0 to 1133
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   id                            1134 non-null   str
 1   developerId                   1134 non-null   int64
 2   treatmentAssignment           1134 non-null   str
 3   status                        1134 non-null   str
 4   priorExperience               1134 non-null   float64
 5   estimatedTimeWithAI           1134 non-null   float64
 6   estimatedTimeWithoutAI        1134 non-null   float64
 7   createdAt                     1134 non-null   str
 8   lastModified                  1134 non-null   str
 9   initialImplementationTime     915 non-null    float64
 10  postReviewImplementationTime  861 non-null    float64
 11  estimatedTimeOtherTreatment   868 non-null    float64
 12  perceivedEffort               888 non-null    float64
 13  isPanelDeveloper              1134 non-null   bool
dtypes: bool(1), float64(7), int64(1), str(5)
memory usage: 116.4 KB

### Import Stack Overflow Data

Because the original dataset is over 100MB, I couldn't push it to GitHub without setting up GitHub LFS, please download the data source from [Stack Overflow Developer Survey 2025](tps://github.com/StackExchange/Survey/blob/main/packages/archive/2025/results.csv) and rename it to `stackoverflowdata.csv` and move it to `data/raw`

In [20]:
stackoverflow_df = pd.read_csv("data/raw/stackoverflowdata.csv")
stackoverflow_df.shape

/var/folders/5k/dqhlcc4j52q82_012tkcvr8w0000gn/T/ipykernel_42694/362504417.py:1: DtypeWarning: Columns (56: JobSatPoints_15_TEXT, 74: DatabaseHaveEntry, 92: DevEnvHaveEntry, 97: SOTagsHaveEntry, 98: SOTagsWant Entry, 105: OfficeStackWantEntry, 109: CommPlatformHaveEntr, 110: CommPlatformWantEntr, 132: SO_Actions_15_TEXT, 162: AIAgentOrchestration, 165: AIAgentObsWrite) have mixed types. Specify dtype option on import or set low_memory=False.
  stackoverflow_df = pd.read_csv("data/raw/stackoverflowdata.csv")

(49191, 172)

In [24]:
stackoverflow_df.head()

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [25]:
stackoverflow_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Columns: 172 entries, ResponseId to JobSat
dtypes: float64(52), int64(1), str(119)
memory usage: 64.6 MB

## Prepare Stack Overflow Data
The Stack Overflow Developer Survey contains a lot of useful information, but it also includes columns that are not relevant to this project. For this part, I will keep only the columns that are useful for my analysis.

In [79]:
# Filter out the columns that are used in the analysis
col_used = [
    "Employment",
    "DevType",
    "WorkExp",
    "YearsCode",
    "LanguageHaveWorkedWith",
    "AISelect",
    "AISent",
    "AIAcc",
    "AIComplex",
    "AIFrustration"
]

stackoverflow_df = stackoverflow_df[col_used].copy()
stackoverflow_df.head()

,Employment,DevType,WorkExp,YearsCode,LanguageHaveWorkedWith,AISelect,AISent,AIAcc,AIComplex,AIFrustration
0,Employed,"Developer, mobile",8.0,14.0,Bash/Shell (all shells);Dart;SQL,"Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,"AI solutions that are almost right, but not quite"
1,Employed,"Developer, back-end",2.0,10.0,Java,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,"AI solutions that are almost right, but not qu..."
2,"Independent contractor, freelancer, or self-em...","Developer, front-end",10.0,12.0,Dart;HTML/CSS;JavaScript;TypeScript,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,"AI solutions that are almost right, but not qu..."
3,Employed,"Developer, back-end",4.0,5.0,Java;Kotlin;SQL,"Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,"AI solutions that are almost right, but not qu..."
4,"Independent contractor, freelancer, or self-em...",Engineering manager,21.0,22.0,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...,"Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks","AI solutions that are almost right, but not quite"

### Import Data From GitHub REST API

For the GitHub analysis, I will use the GitHub REST API to collect pull requests authored by GitHub Copilot. I will examine their merge time and use the number of commits and changed files as additional indicators of pull request size and complexity.

In [ ]:
# Import Copilot-authored merged pull requests from GitHub
url = "https://api.github.com/search/issues"

params = {
    "q": "is:pr is:merged author:@copilot",
    "sort": "created",
    "order": "desc",
    "per_page": 20
}

response = requests.get(url, params=params)
data = response.json()

copilot_prs = []

# Loop through each pull request returned by the search
for pr in data["items"]:
    pr_url = pr["pull_request"]["url"]
    pr_response = requests.get(pr_url)
    
    if pr_response.status_code == 200:
        detail = pr_response.json()
        copilot_prs.append({
            "title": detail["title"],
            "repo_url": pr["repository_url"],
            "created_at": detail["created_at"],
            "merged_at": detail["merged_at"],
            "commits": detail["commits"],
            "changed_files": detail["changed_files"]
        })

copilot_df = pd.DataFrame(copilot_prs)

copilot_df.head()
print(detail)

{'url': 'https://api.github.com/repos/donta79/online-bookstore/pulls/5', 'id': 4621131725, 'node_id': 'PR_kwDOUlDq_88AAAABE3DfzQ', 'html_url': 'https://github.com/donta79/online-bookstore/pull/5', 'diff_url': 'https://github.com/donta79/online-bookstore/pull/5.diff', 'patch_url': 'https://github.com/donta79/online-bookstore/pull/5.patch', 'issue_url': 'https://api.github.com/repos/donta79/online-bookstore/issues/5', 'commits_url': 'https://api.github.com/repos/donta79/online-bookstore/pulls/5/commits', 'review_comments_url': 'https://api.github.com/repos/donta79/online-bookstore/pulls/5/comments', 'review_comment_url': 'https://api.github.com/repos/donta79/online-bookstore/pulls/comments{/number}', 'comments_url': 'https://api.github.com/repos/donta79/online-bookstore/issues/5/comments', 'statuses_url': 'https://api.github.com/repos/donta79/online-bookstore/statuses/e7d05ba719639bacc8c4b1994147d74ec7da3799', 'number': 5, 'state': 'closed', 'locked': False, 'title': 'Add case-insensitive book search across API and UI states', 'user': {'login': 'Copilot', 'id': 198982749, 'node_id': 'BOT_kgDOC9w8XQ', 'avatar_url': 'https://avatars.githubusercontent.com/in/1143301?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Copilot', 'html_url': 'https://github.com/apps/copilot-swe-agent', 'followers_url': 'https://api.github.com/users/Copilot/followers', 'following_url': 'https://api.github.com/users/Copilot/following{/other_user}', 'gists_url': 'https://api.github.com/users/Copilot/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Copilot/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Copilot/subscriptions', 'organizations_url': 'https://api.github.com/users/Copilot/orgs', 'repos_url': 'https://api.github.com/users/Copilot/repos', 'events_url': 'https://api.github.com/users/Copilot/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Copilot/received_events', 'type': 'Bot', 'user_view_type': 'public', 'site_admin': False}, 'body': '## Purpose\nAdds catalogue discovery support via `GET /api/books?q=...` and updates the UI to handle search UX states (loading, error, no results) with structured result cards.\n\n## Related issue\nLinked automatically by the platform.\n\n## Changes\n- **Backend search behavior**\n  - Added optional `q` handling to `GET /api/books`.\n  - Implemented case-insensitive matching across `title`, `author`, and `description`.\n  - Kept blank-query behavior as “return all books”.\n  - Kept no-match behavior as `200` with `[]`.\n  - Search path is read-only and does not mutate catalogue data.\n\n- **Service/repository wiring**\n  - Extended catalogue service + in-memory repository with search filtering logic.\n  - Preserved existing route-to-service delegation and dependency injection pattern.\n\n- **Frontend search UX**\n  - Added a search input and trigger flow in the static UI.\n  - Added explicit loading/error/no-results states.\n  - Replaced plain list rows with result cards showing `title`, `author`, and `availability`.\n\n- **Test coverage**\n  - Added/updated API tests for:\n    - title match\n    - author match\n    - description match\n    - case-insensitive matching\n    - blank query returns all\n    - no match returns empty list\n\n```http\nGET /api/books?q=martin\n```\n\n## Validation\n- [ ] I checked every acceptance criterion.\n- [ ] I ran the relevant tests.\n- [ ] I manually checked the UI and API.\n- [ ] I reviewed the complete diff.\n- [ ] No secrets or unrelated changes are included.\n\n<!-- START COPILOT CODING AGENT SUFFIX -->\n\n- Fixes #4', 'labels': [], 'milestone': None, 'active_lock_reason': None, 'created_at': '2026-09-24T03:19:19Z', 'updated_at': '2026-09-24T03:36:16Z', 'closed_at': '2026-09-24T03:36:16Z', 'merged_at': '2026-09-24T03:36:16Z', 'merge_commit_sha': 'b4608f4c76be6c1adc8f9d70c5c4220cd336b9b2', 'assignee': None, 'assignees': [{'login': 'donta79', 'id': 60910414, 'node_id': 'MDQ6VXNlcjYwOTEwNDE0', 'avatar_url': 'https://avatars.githubusercontent.com/u/60910414?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/donta79', 'html_url': 'https://github.com/donta79', 'followers_url': 'https://api.github.com/users/donta79/followers', 'following_url': 'https://api.github.com/users/donta79/following{/other_user}', 'gists_url': 'https://api.github.com/users/donta79/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/donta79/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/donta79/subscriptions', 'organizations_url': 'https://api.github.com/users/donta79/orgs', 'repos_url': 'https://api.github.com/users/donta79/repos', 'events_url': 'https://api.github.com/users/donta79/events{/privacy}', 'received_events_url': 'https://api.github.com/users/donta79/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, {'login': 'Copilot', 'id': 198982749, 'node_id': 'BOT_kgDOC9w8XQ', 'avatar_url': 'https://avatars.githubusercontent.com/in/1143301?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Copilot', 'html_url': 'https://github.com/apps/copilot-swe-agent', 'followers_url': 'https://api.github.com/users/Copilot/followers', 'following_url': 'https://api.github.com/users/Copilot/following{/other_user}', 'gists_url': 'https://api.github.com/users/Copilot/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Copilot/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Copilot/subscriptions', 'organizations_url': 'https://api.github.com/users/Copilot/orgs', 'repos_url': 'https://api.github.com/users/Copilot/repos', 'events_url': 'https://api.github.com/users/Copilot/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Copilot/received_events', 'type': 'Bot', 'user_view_type': 'public', 'site_admin': False}], 'requested_reviewers': [{'login': 'donta79', 'id': 60910414, 'node_id': 'MDQ6VXNlcjYwOTEwNDE0', 'avatar_url': 'https://avatars.githubusercontent.com/u/60910414?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/donta79', 'html_url': 'https://github.com/donta79', 'followers_url': 'https://api.github.com/users/donta79/followers', 'following_url': 'https://api.github.com/users/donta79/following{/other_user}', 'gists_url': 'https://api.github.com/users/donta79/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/donta79/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/donta79/subscriptions', 'organizations_url': 'https://api.github.com/users/donta79/orgs', 'repos_url': 'https://api.github.com/users/donta79/repos', 'events_url': 'https://api.github.com/users/donta79/events{/privacy}', 'received_events_url': 'https://api.github.com/users/donta79/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}], 'requested_teams': [], 'head': {'label': 'donta79:copilot/search-books', 'ref': 'copilot/search-books', 'repo': {'id': 1381034751, 'node_id': 'R_kgDOUlDq_w', 'name': 'online-bookstore', 'full_name': 'donta79/online-bookstore', 'owner': {'login': 'donta79', 'id': 60910414, 'node_id': 'MDQ6VXNlcjYwOTEwNDE0', 'avatar_url': 'https://avatars.githubusercontent.com/u/60910414?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/donta79', 'html_url': 'https://github.com/donta79', 'followers_url': 'https://api.github.com/users/donta79/followers', 'following_url': 'https://api.github.com/users/donta79/following{/other_user}', 'gists_url': 'https://api.github.com/users/donta79/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/donta79/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/donta79/subscriptions', 'organizations_url': 'https://api.github.com/users/donta79/orgs', 'repos_url': 'https://api.github.com/users/donta79/repos', 'events_url': 'https://api.github.com/users/donta79/events{/privacy}', 'received_events_url': 'https://api.github.com/users/donta79/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'private': False, 'fork': False, 'archived': False, 'disabled': False, 'description': None, 'homepage': None, 'language': 'Python', 'visibility': 'public', 'is_template': False, 'topics': [], 'forks_count': 0, 'forks': 0, 'stargazers_count': 0, 'watchers_count': 0, 'watchers': 0, 'open_issues_count': 5, 'open_issues': 5, 'size': 12, 'default_branch': 'main', 'has_issues': True, 'has_projects': True, 'has_wiki': True, 'has_pages': False, 'has_downloads': False, 'has_discussions': False, 'has_pull_requests': True, 'pushed_at': '2026-09-24T03:36:16Z', 'created_at': '2026-09-22T07:16:49Z', 'updated_at': '2026-09-24T03:36:21Z', 'allow_forking': True, 'web_commit_signoff_required': False, 'pull_request_creation_policy': 'all', 'license': None, 'url': 'https://api.github.com/repos/donta79/online-bookstore', 'html_url': 'https://github.com/donta79/online-bookstore', 'archive_url': 'https://api.github.com/repos/donta79/online-bookstore/{archive_format}{/ref}', 'assignees_url': 'https://api.github.com/repos/donta79/online-bookstore/assignees{/user}', 'blobs_url': 'https://api.github.com/repos/donta79/online-bookstore/git/blobs{/sha}', 'branches_url': 'https://api.github.com/repos/donta79/online-bookstore/branches{/branch}', 'collaborators_url': 'https://api.github.com/repos/donta79/online-bookstore/collaborators{/collaborator}', 'comments_url': 'https://api.github.com/repos/donta79/online-bookstore/comments{/number}', 'commits_url': 'https://api.github.com/repos/donta79/online-bookstore/commits{/sha}', 'compare_url': 'https://api.github.com/repos/donta79/online-bookstore/compare/{base}...{head}', 'contents_url': 'https://api.github.com/repos/donta79/online-bookstore/contents/{+path}', 'contributors_url': 'https://api.github.com/repos/donta79/online-bookstore/contributors', 'deployments_url': 'https://api.github.com/repos/donta79/online-bookstore/deployments', 'downloads_url': 'https://api.github.com/repos/donta79/online-bookstore/downloads', 'events_url': 'https://api.github.com/repos/donta79/online-bookstore/events', 'forks_url': 'https://api.github.com/repos/donta79/online-bookstore/forks', 'git_commits_url': 'https://api.github.com/repos/donta79/online-bookstore/git/commits{/sha}', 'git_refs_url': 'https://api.github.com/repos/donta79/online-bookstore/git/refs{/sha}', 'git_tags_url': 'https://api.github.com/repos/donta79/online-bookstore/git/tags{/sha}', 'git_url': 'git://github.com/donta79/online-bookstore.git', 'issue_comment_url': 'https://api.github.com/repos/donta79/online-bookstore/issues/comments{/number}', 'issue_events_url': 'https://api.github.com/repos/donta79/online-bookstore/issues/events{/number}', 'issues_url': 'https://api.github.com/repos/donta79/online-bookstore/issues{/number}', 'keys_url': 'https://api.github.com/repos/donta79/online-bookstore/keys{/key_id}', 'labels_url': 'https://api.github.com/repos/donta79/online-bookstore/labels{/name}', 'languages_url': 'https://api.github.com/repos/donta79/online-bookstore/languages', 'merges_url': 'https://api.github.com/repos/donta79/online-bookstore/merges', 'milestones_url': 'https://api.github.com/repos/donta79/online-bookstore/milestones{/number}', 'notifications_url': 'https://api.github.com/repos/donta79/online-bookstore/notifications{?since,all,participating}', 'pulls_url': 'https://api.github.com/repos/donta79/online-bookstore/pulls{/number}', 'releases_url': 'https://api.github.com/repos/donta79/online-bookstore/releases{/id}', 'ssh_url': 'git@github.com:donta79/online-bookstore.git', 'stargazers_url': 'https://api.github.com/repos/donta79/online-bookstore/stargazers', 'statuses_url': 'https://api.github.com/repos/donta79/online-bookstore/statuses/{sha}', 'subscribers_url': 'https://api.github.com/repos/donta79/online-bookstore/subscribers', 'subscription_url': 'https://api.github.com/repos/donta79/online-bookstore/subscription', 'tags_url': 'https://api.github.com/repos/donta79/online-bookstore/tags', 'teams_url': 'https://api.github.com/repos/donta79/online-bookstore/teams', 'trees_url': 'https://api.github.com/repos/donta79/online-bookstore/git/trees{/sha}', 'clone_url': 'https://github.com/donta79/online-bookstore.git', 'mirror_url': None, 'hooks_url': 'https://api.github.com/repos/donta79/online-bookstore/hooks', 'svn_url': 'https://github.com/donta79/online-bookstore'}, 'sha': 'e7d05ba719639bacc8c4b1994147d74ec7da3799', 'user': {'login': 'donta79', 'id': 60910414, 'node_id': 'MDQ6VXNlcjYwOTEwNDE0', 'avatar_url': 'https://avatars.githubusercontent.com/u/60910414?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/donta79', 'html_url': 'https://github.com/donta79', 'followers_url': 'https://api.github.com/users/donta79/followers', 'following_url': 'https://api.github.com/users/donta79/following{/other_user}', 'gists_url': 'https://api.github.com/users/donta79/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/donta79/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/donta79/subscriptions', 'organizations_url': 'https://api.github.com/users/donta79/orgs', 'repos_url': 'https://api.github.com/users/donta79/repos', 'events_url': 'https://api.github.com/users/donta79/events{/privacy}', 'received_events_url': 'https://api.github.com/users/donta79/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}}, 'base': {'label': 'donta79:main', 'ref': 'main', 'repo': {'id': 1381034751, 'node_id': 'R_kgDOUlDq_w', 'name': 'online-bookstore', 'full_name': 'donta79/online-bookstore', 'owner': {'login': 'donta79', 'id': 60910414, 'node_id': 'MDQ6VXNlcjYwOTEwNDE0', 'avatar_url': 'https://avatars.githubusercontent.com/u/60910414?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/donta79', 'html_url': 'https://github.com/donta79', 'followers_url': 'https://api.github.com/users/donta79/followers', 'following_url': 'https://api.github.com/users/donta79/following{/other_user}', 'gists_url': 'https://api.github.com/users/donta79/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/donta79/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/donta79/subscriptions', 'organizations_url': 'https://api.github.com/users/donta79/orgs', 'repos_url': 'https://api.github.com/users/donta79/repos', 'events_url': 'https://api.github.com/users/donta79/events{/privacy}', 'received_events_url': 'https://api.github.com/users/donta79/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'private': False, 'fork': False, 'archived': False, 'disabled': False, 'description': None, 'homepage': None, 'language': 'Python', 'visibility': 'public', 'is_template': False, 'topics': [], 'forks_count': 0, 'forks': 0, 'stargazers_count': 0, 'watchers_count': 0, 'watchers': 0, 'open_issues_count': 5, 'open_issues': 5, 'size': 12, 'default_branch': 'main', 'has_issues': True, 'has_projects': True, 'has_wiki': True, 'has_pages': False, 'has_downloads': False, 'has_discussions': False, 'has_pull_requests': True, 'pushed_at': '2026-09-24T03:36:16Z', 'created_at': '2026-09-22T07:16:49Z', 'updated_at': '2026-09-24T03:36:21Z', 'allow_forking': True, 'web_commit_signoff_required': False, 'pull_request_creation_policy': 'all', 'license': None, 'url': 'https://api.github.com/repos/donta79/online-bookstore', 'html_url': 'https://github.com/donta79/online-bookstore', 'archive_url': 'https://api.github.com/repos/donta79/online-bookstore/{archive_format}{/ref}', 'assignees_url': 'https://api.github.com/repos/donta79/online-bookstore/assignees{/user}', 'blobs_url': 'https://api.github.com/repos/donta79/online-bookstore/git/blobs{/sha}', 'branches_url': 'https://api.github.com/repos/donta79/online-bookstore/branches{/branch}', 'collaborators_url': 'https://api.github.com/repos/donta79/online-bookstore/collaborators{/collaborator}', 'comments_url': 'https://api.github.com/repos/donta79/online-bookstore/comments{/number}', 'commits_url': 'https://api.github.com/repos/donta79/online-bookstore/commits{/sha}', 'compare_url': 'https://api.github.com/repos/donta79/online-bookstore/compare/{base}...{head}', 'contents_url': 'https://api.github.com/repos/donta79/online-bookstore/contents/{+path}', 'contributors_url': 'https://api.github.com/repos/donta79/online-bookstore/contributors', 'deployments_url': 'https://api.github.com/repos/donta79/online-bookstore/deployments', 'downloads_url': 'https://api.github.com/repos/donta79/online-bookstore/downloads', 'events_url': 'https://api.github.com/repos/donta79/online-bookstore/events', 'forks_url': 'https://api.github.com/repos/donta79/online-bookstore/forks', 'git_commits_url': 'https://api.github.com/repos/donta79/online-bookstore/git/commits{/sha}', 'git_refs_url': 'https://api.github.com/repos/donta79/online-bookstore/git/refs{/sha}', 'git_tags_url': 'https://api.github.com/repos/donta79/online-bookstore/git/tags{/sha}', 'git_url': 'git://github.com/donta79/online-bookstore.git', 'issue_comment_url': 'https://api.github.com/repos/donta79/online-bookstore/issues/comments{/number}', 'issue_events_url': 'https://api.github.com/repos/donta79/online-bookstore/issues/events{/number}', 'issues_url': 'https://api.github.com/repos/donta79/online-bookstore/issues{/number}', 'keys_url': 'https://api.github.com/repos/donta79/online-bookstore/keys{/key_id}', 'labels_url': 'https://api.github.com/repos/donta79/online-bookstore/labels{/name}', 'languages_url': 'https://api.github.com/repos/donta79/online-bookstore/languages', 'merges_url': 'https://api.github.com/repos/donta79/online-bookstore/merges', 'milestones_url': 'https://api.github.com/repos/donta79/online-bookstore/milestones{/number}', 'notifications_url': 'https://api.github.com/repos/donta79/online-bookstore/notifications{?since,all,participating}', 'pulls_url': 'https://api.github.com/repos/donta79/online-bookstore/pulls{/number}', 'releases_url': 'https://api.github.com/repos/donta79/online-bookstore/releases{/id}', 'ssh_url': 'git@github.com:donta79/online-bookstore.git', 'stargazers_url': 'https://api.github.com/repos/donta79/online-bookstore/stargazers', 'statuses_url': 'https://api.github.com/repos/donta79/online-bookstore/statuses/{sha}', 'subscribers_url': 'https://api.github.com/repos/donta79/online-bookstore/subscribers', 'subscription_url': 'https://api.github.com/repos/donta79/online-bookstore/subscription', 'tags_url': 'https://api.github.com/repos/donta79/online-bookstore/tags', 'teams_url': 'https://api.github.com/repos/donta79/online-bookstore/teams', 'trees_url': 'https://api.github.com/repos/donta79/online-bookstore/git/trees{/sha}', 'clone_url': 'https://github.com/donta79/online-bookstore.git', 'mirror_url': None, 'hooks_url': 'https://api.github.com/repos/donta79/online-bookstore/hooks', 'svn_url': 'https://github.com/donta79/online-bookstore'}, 'sha': '68cd90b129acdc690e4f903ceff999fdeeb1cd72', 'user': {'login': 'donta79', 'id': 60910414, 'node_id': 'MDQ6VXNlcjYwOTEwNDE0', 'avatar_url': 'https://avatars.githubusercontent.com/u/60910414?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/donta79', 'html_url': 'https://github.com/donta79', 'followers_url': 'https://api.github.com/users/donta79/followers', 'following_url': 'https://api.github.com/users/donta79/following{/other_user}', 'gists_url': 'https://api.github.com/users/donta79/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/donta79/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/donta79/subscriptions', 'organizations_url': 'https://api.github.com/users/donta79/orgs', 'repos_url': 'https://api.github.com/users/donta79/repos', 'events_url': 'https://api.github.com/users/donta79/events{/privacy}', 'received_events_url': 'https://api.github.com/users/donta79/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}}, '_links': {'comments': {'href': 'https://api.github.com/repos/donta79/online-bookstore/issues/5/comments'}, 'commits': {'href': 'https://api.github.com

## Resources and References
*What resources and references have you used for this project?*
📝 <!-- Answer Below -->

[Open Source Developer Productivity - Late 2025 Follow-on Study Results ](https://github.com/METR/Measuring-Late-2025-AI-on-OSS-Devs)

[Stack Overflow Developer Survey](https://github.com/StackExchange/Survey)

[GitHub REST API](https://docs.github.com/en/rest?apiVersion=2026-03-10)

## AI Use Disclosure

I used AI tools to refine project scope and data analysis ideas, improve written explanations. I also used AI to help compare my project scope with the available datasets to ensure the data I selected could actually help answer the questions. I reviewed the final analysis, interpretations, and conclusions myself.

In [4]:
# ⚠️ Make sure you run this cell at the end of your notebook before every submission!
!jupyter nbconvert --to python source.ipynb

[NbConvertApp] Converting notebook source.ipynb to python
[NbConvertApp] Writing 5397 bytes to source.py